jest.mock("~/server/db", () => ({ db: { transaction: jest.fn() } }));
import { eq } from "drizzle-orm";
import { company } from "@launchstack/core/db/schema";
import { founderWeeklyReviewDispatches, founderWeeklyReviewRuns } from "~/server/db/schema";
import { FounderWeeklyReviewEvidenceSnapshotSchema, FounderWeeklyReviewRepository, FounderWeeklyReviewWorkerService } from "@launchstack/features/founder-weekly-review";
import { createFounderWeeklyReviewDispatchService } from "~/server/founder-weekly-review/dispatch-service";
import { createFounderWeeklyReviewTestDatabase } from "./testDb";

const describeDb = process.env.LAUNCHSTACK_TEST_DATABASE_URL || process.env.DATABASE_URL ? describe : describe.skip;
const snapshot = FounderWeeklyReviewEvidenceSnapshotSchema.parse({ schemaVersion: "founder-weekly-review-evidence/v1", capturedAt: "2026-07-13T00:00:00.000Z", reportingPeriod: { start: "2026-07-06", end: "2026-07-12" }, workspaceTimezone: "UTC", items: [], sourceWarnings: [] });
const actor = (companyId: bigint) => ({ externalUserId: "u", internalUserId: 1n, companyId, role: "owner" as const });
async function companyId(db: Awaited<ReturnType<typeof createFounderWeeklyReviewTestDatabase>>["db"]): Promise<bigint> { const [row] = await db.insert(company).values({ name: "Atomic", numberOfEmployees: "1" }).returning(); return BigInt(row!.id); }

describeDb("Founder Weekly Review dispatch atomicity", () => {
 it("concurrent create persists one run and one dispatch", async () => { const test = await createFounderWeeklyReviewTestDatabase(); const a = await test.createSession(), b = await test.createSession(); try { const id = await companyId(test.db); const input = { actor: actor(id), requestKey: "create-race", reportingPeriod: snapshot.reportingPeriod, evidenceSnapshot: snapshot }; const results = await Promise.all([createFounderWeeklyReviewDispatchService(a.db).createRunWithDispatch(input), createFounderWeeklyReviewDispatchService(b.db).createRunWithDispatch(input)]); const rows = await test.db.select().from(founderWeeklyReviewRuns); const dispatches = await test.db.select().from(founderWeeklyReviewDispatches); expect(rows).toHaveLength(1); expect(dispatches).toHaveLength(1); expect(results.map(x => x.created).sort()).toEqual([false, true]); expect(new Set(results.map(x => x.run.id)).size).toBe(1); expect(FounderWeeklyReviewEvidenceSnapshotSchema.parse(rows[0]!.evidenceSnapshot)).toEqual(snapshot); } finally { await a.close(); await b.close(); await test.close(); } });
 it("concurrent retry transitions once and preserves snapshot", async () => { const test = await createFounderWeeklyReviewTestDatabase(); const a = await test.createSession(), b = await test.createSession(); try { const id = await companyId(test.db); const repo = new FounderWeeklyReviewRepository(test.db); const created = await repo.createOrGetByRequestKey({ id: "fwr_failed", companyId: id, requestKey: "base", reportingPeriod: snapshot.reportingPeriod, evidenceSnapshot: snapshot, createdByActorId: "user:u" }); await new FounderWeeklyReviewWorkerService(repo).markQueuedRunFailed(id, created.id, { errorCode: "x" }); const input = { actor: actor(id), runId: created.id, requestKey: "retry-race" }; const results = await Promise.all([createFounderWeeklyReviewDispatchService(a.db).retryRunWithDispatch(input), createFounderWeeklyReviewDispatchService(b.db).retryRunWithDispatch(input)]); const [row] = await test.db.select().from(founderWeeklyReviewRuns).where(eq(founderWeeklyReviewRuns.id, created.id)); const dispatches = await test.db.select().from(founderWeeklyReviewDispatches).where(eq(founderWeeklyReviewDispatches.operationType, "retry")); expect(results.map(x => x.transitionApplied).sort()).toEqual([false, true]); expect(row!.status).toBe("queued"); expect(row!.retryCount).toBe(1); expect(row!.evidenceSnapshot).toEqual(snapshot); expect(dispatches).toHaveLength(1); } finally { await a.close(); await b.close(); await test.close(); } });
 it("rolls back create when dispatch persistence fails", async () => { const test = await createFounderWeeklyReviewTestDatabase(); try { const id = await companyId(test.db); const service = createFounderWeeklyReviewDispatchService(test.db, { createDispatch: async () => { throw new Error("forced_dispatch_insert_failure"); } }); await expect(service.createRunWithDispatch({ actor: actor(id), requestKey: "rollback", reportingPeriod: snapshot.reportingPeriod, evidenceSnapshot: snapshot })).rejects.toThrow("forced_dispatch_insert_failure"); expect(await test.db.select().from(founderWeeklyReviewRuns)).toHaveLength(0); expect(await test.db.select().from(founderWeeklyReviewDispatches)).toHaveLength(0); } finally { await test.close(); } });
 it("rolls back retry when dispatch persistence fails", async () => { const test = await createFounderWeeklyReviewTestDatabase(); try { const id = await companyId(test.db); const repo = new FounderWeeklyReviewRepository(test.db); const created = await repo.createOrGetByRequestKey({ id: "fwr_retry_rollback", companyId: id, requestKey: "base", reportingPeriod: snapshot.reportingPeriod, evidenceSnapshot: snapshot, createdByActorId: "user:u" }); await new FounderWeeklyReviewWorkerService(repo).markQueuedRunFailed(id, created.id, { errorCode: "x" }); const service = createFounderWeeklyReviewDispatchService(test.db, { createDispatch: async () => { throw new Error("forced_dispatch_insert_failure"); } }); await expect(service.retryRunWithDispatch({ actor: actor(id), runId: created.id, requestKey: "retry" })).rejects.toThrow("forced_dispatch_insert_failure"); const [row] = await test.db.select().from(founderWeeklyReviewRuns).where(eq(founderWeeklyReviewRuns.id, created.id)); expect(row!.status).toBe("failed"); expect(row!.retryCount).toBe(0); expect(row!.evidenceSnapshot).toEqual(snapshot); expect(await test.db.select().from(founderWeeklyReviewDispatches)).toHaveLength(0); } finally { await test.close(); } });
});
