import type { ReactNode } from "react";
import {
    Archive,
    ArrowDownWideNarrow,
    ArrowRightLeft,
    ArrowUpNarrowWide,
    Bell,
    Bookmark,
    Brain,
    Check,
    ClipboardPaste,
    Clock,
    Code,
    Command,
    Copy,
    Download,
    Eraser,
    ExternalLink,
    Eye,
    EyeOff,
    FileOutput,
    FileText,
    Flag,
    Folder,
    FolderOpen,
    GitBranch,
    GitCompare,
    Globe,
    History,
    Image,
    Import,
    Languages,
    Layers,
    Lightbulb,
    Link,
    ListChecks,
    ListFilter,
    Lock,
    LogOut,
    Mail,
    Maximize2,
    MessageSquare,
    MessageSquarePlus,
    Monitor,
    Moon,
    Palette,
    PanelLeft,
    Paperclip,
    Pencil,
    Pin,
    Play,
    Plus,
    Quote,
    RefreshCw,
    RotateCcw,
    Scissors,
    ScrollText,
    Search,
    Send,
    Settings,
    Shapes,
    ShieldCheck,
    Sparkles,
    Square,
    Star,
    StickyNote,
    Sun,
    SunMoon,
    Table,
    Tag,
    Terminal,
    Trash2,
    Undo2,
    Unplug,
    Upload,
    User,
    UserMinus,
    UserPlus,
    Users,
    Workflow,
    type LucideIcon,
} from "lucide-react";

/**
 * Menu icons are named, not passed as nodes, so item lists stay plain data
 * (serialisable, comparable in tests) and every menu draws from one set.
 */
export const ACTION_MENU_ICONS = {
    // The original rail set.
    open: Eye,
    ask: Sparkles,
    rename: Pencil,
    copy: Copy,
    delete: Trash2,
    folder: Folder,
    plus: Plus,
    check: Check,
    lock: Lock,
    share: Users,
    // Navigation and links.
    external: ExternalLink,
    link: Link,
    reveal: FolderOpen,
    sidebar: PanelLeft,
    command: Command,
    expand: Maximize2,
    // Files and data.
    download: Download,
    upload: Upload,
    import: Import,
    export: FileOutput,
    file: FileText,
    image: Image,
    code: Code,
    table: Table,
    refresh: RefreshCw,
    history: History,
    restore: Undo2,
    compare: GitCompare,
    archive: Archive,
    // Editing and clipboard.
    cut: Scissors,
    paste: ClipboardPaste,
    attach: Paperclip,
    eraser: Eraser,
    quote: Quote,
    note: StickyNote,
    tag: Tag,
    select: ListChecks,
    // Chat and AI.
    chat: MessageSquare,
    newChat: MessageSquarePlus,
    branch: GitBranch,
    retry: RotateCcw,
    send: Send,
    brain: Brain,
    globe: Globe,
    explain: Lightbulb,
    translate: Languages,
    transcript: ScrollText,
    mindmap: Workflow,
    shapes: Shapes,
    // Organising and status.
    star: Star,
    pin: Pin,
    bookmark: Bookmark,
    flag: Flag,
    bell: Bell,
    clock: Clock,
    search: Search,
    filter: ListFilter,
    group: Layers,
    sortAsc: ArrowUpNarrowWide,
    sortDesc: ArrowDownWideNarrow,
    hide: EyeOff,
    move: ArrowRightLeft,
    play: Play,
    stop: Square,
    terminal: Terminal,
    // People, settings, chrome.
    user: User,
    userPlus: UserPlus,
    userMinus: UserMinus,
    mail: Mail,
    settings: Settings,
    scopes: ShieldCheck,
    disconnect: Unplug,
    logout: LogOut,
    palette: Palette,
    theme: SunMoon,
    sun: Sun,
    moon: Moon,
    monitor: Monitor,
} satisfies Record<string, LucideIcon>;

export type ActionMenuIconName = keyof typeof ACTION_MENU_ICONS;

export const ACTION_MENU_ICON_SIZE = 13;

export function iconFor(name: ActionMenuIconName | undefined): ReactNode {
    if (!name) return null;
    const Icon = ACTION_MENU_ICONS[name];
    return <Icon size={ACTION_MENU_ICON_SIZE} aria-hidden />;
}
